/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health check
         * @description Public endpoint. Returns API + dependency status.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All services healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
                /** @description One or more services degraded */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List supported chains */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Chain list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            chains: components["schemas"]["Chain"][];
                            count: number;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/allowances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List token approvals for a wallet */
        get: {
            parameters: {
                query: {
                    wallet: components["parameters"]["WalletQuery"];
                    chainId?: number;
                    riskOnly?: boolean;
                    page?: number;
                    pageSize?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated allowances */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AllowancesResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk-score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated wallet risk score */
        get: {
            parameters: {
                query: {
                    wallet: components["parameters"]["WalletQuery"];
                    chainId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Risk score and breakdown */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RiskScoreResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cross-chain portfolio risk */
        get: {
            parameters: {
                query: {
                    wallet: components["parameters"]["WalletQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Portfolio risk with per-chain breakdown and benchmark */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PortfolioRiskResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/risk-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pre-signing risk assessment for a proposed approval
         * @description Call this BEFORE a user signs an `approve()` transaction to surface known spender / unlimited-amount risks.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RiskCheckRequest"];
                };
            };
            responses: {
                /** @description Risk assessment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RiskCheckResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger an on-chain scan for a wallet */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ScanRequest"];
                };
            };
            responses: {
                /** @description Scan already running for this wallet */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            wallet?: components["schemas"]["Address"];
                        };
                    };
                };
                /** @description Scan queued */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScanResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate revoking approvals (time machine)
         * @description Returns a before/after risk comparison without actually changing state.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SimulateRequest"];
                };
            };
            responses: {
                /** @description Simulation result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimulateResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Lowercased EVM address
         * @example 0x742d35cc6634c0532925a3b844bc9e7595f0beb6
         */
        Address: string;
        /** @description EIP-155 chain ID */
        ChainId: number;
        /** @enum {string} */
        RiskLevel: "safe" | "low" | "medium" | "high" | "critical";
        Error: {
            error: string;
            code?: string;
            details?: unknown;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "healthy" | "degraded";
            /** @constant */
            version: "v1";
            services: {
                [key: string]: "ok" | "degraded" | "down";
            };
            /** Format: date-time */
            timestamp: string;
        };
        Chain: {
            chainId: components["schemas"]["ChainId"];
            name: string;
            symbol: string;
            /** Format: uri */
            explorer: string;
        };
        Allowance: {
            chain_id: components["schemas"]["ChainId"];
            token_address: components["schemas"]["Address"];
            spender_address: components["schemas"]["Address"];
            /** @example ERC20 */
            standard: string;
            allowance_type: string;
            /** @description Raw integer amount as a decimal string */
            amount: string;
            is_unlimited: boolean;
            last_seen_block: number;
            risk_score: number;
            risk_flags?: string[] | null;
            token_name?: string | null;
            token_symbol?: string | null;
            token_decimals?: number | null;
            spender_label?: string | null;
            spender_trust?: string | null;
        };
        Pagination: {
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
        };
        AllowancesResponse: {
            allowances: components["schemas"]["Allowance"][];
            pagination: components["schemas"]["Pagination"];
        };
        RiskScoreResponse: {
            wallet: components["schemas"]["Address"];
            chainId: components["schemas"]["ChainId"] | "all";
            riskScore: number;
            riskLevel: components["schemas"]["RiskLevel"];
            breakdown: {
                totalAllowances?: number;
                unlimitedAllowances?: number;
                highRisk?: number;
                mediumRisk?: number;
                lowRisk?: number;
                maxIndividualScore?: number;
                avgRiskScore?: number;
                chainsWithAllowances?: number;
            };
            topRisks: {
                chain_id?: components["schemas"]["ChainId"];
                token_address?: components["schemas"]["Address"];
                spender_address?: components["schemas"]["Address"];
                risk_score?: number;
                risk_flags?: string[] | null;
                is_unlimited?: boolean;
                token_symbol?: string | null;
                spender_label?: string | null;
            }[];
        };
        PortfolioRiskResponse: {
            wallet: components["schemas"]["Address"];
            portfolioRiskScore: number;
            riskLevel: components["schemas"]["RiskLevel"];
            summary: {
                chainsWithAllowances?: number;
                totalAllowances?: number;
                unlimitedAllowances?: number;
                highRiskAllowances?: number;
                permit2Allowances?: number;
                estimatedTotalValueUsd?: number;
            };
            trend: {
                /** @enum {string} */
                direction?: "improving" | "worsening" | "stable";
                deltaScore?: number;
                period?: string;
                message?: string;
            };
            benchmark: {
                saferThanPercent?: number;
                message?: string;
                totalWalletsCompared?: number;
            };
            chainBreakdown: {
                chainId?: components["schemas"]["ChainId"];
                chainName?: string;
                totalAllowances?: number;
                unlimitedAllowances?: number;
                highRiskCount?: number;
                estimatedValueUsd?: number;
                riskScore?: number;
                permit2Allowances?: number;
            }[];
        };
        RiskCheckRequest: {
            token: components["schemas"]["Address"];
            spender: components["schemas"]["Address"];
            chainId: components["schemas"]["ChainId"];
            /** @description Raw amount or the literal "unlimited" */
            amount?: string;
        };
        RiskCheckResponse: {
            chainId?: components["schemas"]["ChainId"];
            token?: {
                address?: components["schemas"]["Address"];
                name?: string | null;
                symbol?: string | null;
                decimals?: number | null;
            };
            spender?: {
                address?: components["schemas"]["Address"];
                label?: string | null;
                trusted?: boolean;
                affectedWallets?: number;
            };
            approval?: {
                amount?: string | null;
                isUnlimited?: boolean;
            };
            risk?: {
                score?: number;
                level?: components["schemas"]["RiskLevel"];
                flags?: {
                    code?: string;
                    /** @enum {string} */
                    severity?: "low" | "medium" | "high" | "critical";
                    message?: string;
                }[];
            };
            recommendation?: string;
        };
        ScanRequest: {
            wallet: components["schemas"]["Address"];
            chains?: components["schemas"]["ChainId"][];
        };
        ScanResponse: {
            scanId: number;
            wallet: components["schemas"]["Address"];
            chains: components["schemas"]["ChainId"][];
            /** @enum {string} */
            status: "pending" | "running" | "complete" | "failed";
            statusUrl: string;
        };
        SimulateRequest: {
            wallet: components["schemas"]["Address"];
            chainId?: components["schemas"]["ChainId"];
            /** @default false */
            revokeAll: boolean;
            revokeSpenders?: components["schemas"]["Address"][];
        };
        SimulateResponse: {
            wallet: components["schemas"]["Address"];
            chainId: components["schemas"]["ChainId"] | "all";
            simulation: {
                before?: components["schemas"]["SimulateStats"];
                after?: components["schemas"]["SimulateStats"];
                improvement?: {
                    scoreReduction?: number;
                    allowancesRevoked?: number;
                    percentImprovement?: number;
                };
            };
        };
        SimulateStats: {
            riskScore?: number;
            totalAllowances?: number;
            unlimitedAllowances?: number;
            highRisk?: number;
            mediumRisk?: number;
        };
    };
    responses: {
        /** @description Validation failed */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing, invalid, or revoked API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit exceeded (daily or burst) */
        RateLimited: {
            headers: {
                /** @description Seconds until the limit resets */
                "Retry-After"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        WalletQuery: components["schemas"]["Address"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
