'use client'

import { useEffect, useState } from 'react'
import Head from 'next/head'

type Item = {
  chain_id: number
  token_address: string
  spender_address: string
  standard: string
  allowance_type: string
  amount: string
  is_unlimited: boolean
  badges: string[]
}

export default function SharePage({ params }: { params: Promise<{ token: string }> }) {
  const [data, setData] = useState<{ wallet: string; risk_only: boolean; expires_at: string | null; items: Item[] } | null>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    ;(async () => {
      try {
        const { token } = await params
        const r = await fetch(`/api/share/${token}`)
        const j = await r.json()
        if (!r.ok) throw new Error(j.error || 'Error')
        setData(j)
      } catch (e: unknown) {
        setError(e instanceof Error ? e.message : 'Failed to load')
      }
    })()
  }, [params])

  return (
    <main className="mx-auto max-w-4xl px-6 py-10 bg-paper-deep min-h-screen">
      {/* noindex */}
      <Head>
        <meta name="robots" content="noindex,nofollow" />
      </Head>

      <h1 className="text-2xl font-semibold text-ink">Allowance Guard — Shared Report</h1>
      {error && <div className="mt-4 rounded bg-red-50 dark:bg-red-900/20 px-3 py-2 text-sm text-red-700 dark:text-red-300">{error}</div>}
      {!data && !error && <div className="mt-4 text-sm text-ink-muted">Loading…</div>}

      {data && (
        <>
          <p className="text-sm text-ink-muted mt-2">
            Wallet: <span className="font-mono break-all">{data.wallet}</span>
            {data.risk_only ? ' • Risky approvals only' : ' • All approvals'}
            {data.expires_at ? ` • Expires: ${new Date(data.expires_at).toLocaleString()}` : ' • No expiry'}
          </p>
          <div className="mt-6 overflow-x-auto">
            <table className="w-full text-sm text-ink">
              <thead className="text-left">
                <tr className="border-b border-ink-rule">
                  <th className="pb-2 pr-4">Chain</th><th className="pb-2 pr-4">Token</th><th className="pb-2 pr-4">Spender</th><th className="pb-2 pr-4">Std</th><th className="pb-2 pr-4">Type</th><th className="pb-2 pr-4">Amount</th><th className="pb-2">Badges</th>
                </tr>
              </thead>
              <tbody>
                {data.items.map((r, i) => (
                  <tr key={i} className="border-t border-ink-rule">
                    <td className="py-2 pr-4">{r.chain_id}</td>
                    <td className="font-mono break-all py-2 pr-4">{r.token_address}</td>
                    <td className="font-mono break-all py-2 pr-4">{r.spender_address}</td>
                    <td className="py-2 pr-4">{r.standard}</td>
                    <td className="py-2 pr-4">{r.allowance_type}</td>
                    <td className="font-mono py-2 pr-4">{r.amount}</td>
                    <td className="space-x-1 py-2">{r.badges.map((b, j) => (
                      <span key={j} className={`rounded px-2 py-0.5 text-xs ${
                        b==='UNLIMITED' ? 'bg-crimson/10 text-crimson' : 'bg-amber/10 text-amber'
                      }`}>{b}</span>
                    ))}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="mt-4 text-xs text-ink-whisper">Read-only. Generated by Allowance Guard.</p>
        </>
      )}
    </main>
  )
}
